services:
  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /:/host:ro,rslave
    pid: "host"
    network_mode: "host"
    command:
      - "--path.rootfs=/host"

networks:
  db-net:
    driver: bridge
